"use server";

type GenerateCoverLetterInput = {
  jobTitle: string;
  companyName: string;
  jobDescription: string;
};


import { prisma } from "@/lib/prisma";
import { auth } from "@clerk/nextjs/server";
import OpenAI from "openai";

const ai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY!,
});

export async function generateCoverLetter(data:GenerateCoverLetterInput) {
  const { userId } = await auth();
  if (!userId) throw new Error("Unauthorized");

  const user = await prisma.user.findUnique({
    where: { clerkUserId: userId },
  });

  if (!user) throw new Error("User not found");

 const prompt = `
You are a senior career coach and professional resume writer.

Write a tailored, high-impact cover letter for the position of **${data.jobTitle}** at **${data.companyName}**.

### Candidate Profile
- Industry: ${user.industry}
- Years of Experience: ${user.experience}
- Core Skills: ${user.skills?.join(", ")}
- Professional Background Summary: ${user.bio}

### Job Description
${data.jobDescription}

### Writing Guidelines
- Use a confident, professional, and enthusiastic tone
- Focus only on skills and experiences that are **directly relevant** to the role
- Explicitly connect the candidate’s background to the company’s needs and job requirements
- Include **1–2 specific, realistic, and quantified achievements** (metrics, outcomes, or impact)
- Avoid clichés, buzzwords, and generic phrases
- Do NOT repeat the resume — explain **why** the candidate is a strong fit
- Keep the total length under **400 words**

### Formatting Requirements
- Use **proper business cover letter structure**
- Format the output in **Markdown**
- Include the following sections:
  - Greeting
  - Introduction (role + interest in the company)
  - Body (skills, experience, achievements aligned to the role)
  - Closing (enthusiasm + call to action)
  - Professional sign-off

### Final Check
Ensure the letter feels:
- Personalized (not generic)
- Results-driven
- ATS-friendly
- Suitable for immediate submission

Return only the completed cover letter in Markdown format.
`;


  try {
    const result = await ai.responses.create({
      model: "gpt-4.1-mini",
      input: prompt,
    });
 const content = result.output_text?.trim();
if (!content) {
  throw new Error("No content generated by AI");
}

    const coverLetter = await prisma.coverLetter.create({
      data: {
        content,
        jobDescription: data.jobDescription,
        companyName: data.companyName,
        jobTitle: data.jobTitle,
        status: "completed",
        userId: user.id,
      },
    });

    return coverLetter;
  } catch (error) {
    console.error("Error generating cover letter:",(error as Error ).message);
    throw new Error("Failed to generate cover letter");
  }
}

export async function getCoverLetters() {
  const { userId } = await auth();
  if (!userId) throw new Error("Unauthorized");

  const user = await prisma.user.findUnique({
    where: { clerkUserId: userId },
  });

  if (!user) throw new Error("User not found");

  return await prisma.coverLetter.findMany({
    where: {
      userId: user.id,
    },
    orderBy: {
      createdAt: "desc",
    },
  });
}

export async function getCoverLetter(id:string) {
  const { userId } = await auth();
  if (!userId) throw new Error("Unauthorized");

  const user = await prisma.user.findUnique({
    where: { clerkUserId: userId },
  });

  if (!user) throw new Error("User not found");

  return await prisma.coverLetter.findUnique({
    where: {
      id,
      userId: user.id,
    },
  });
}

export async function deleteCoverLetter(id:string) {
  const { userId } = await auth();
  if (!userId) throw new Error("Unauthorized");

  const user = await prisma.user.findUnique({
    where: { clerkUserId: userId },
  });

  if (!user) throw new Error("User not found");

  return await prisma.coverLetter.delete({
    where: {
      id,
      userId: user.id,
    },
  });
}